name = "polysat2"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Polysat2"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "Hammer"
git = "https://github.com/JOSHCLUNE/LeanHammer"
rev = "v4.21.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.21.0"

[[require]]
name = "Canonical"
scope = "chasenorman"

[[lean_lib]]
name = "Polysat2"
